# Use the base image from the given configuration
FROM ghcr.io/gethomepage/homepage:latest

# Set the working directory
WORKDIR /app

# Copy the local config directory to the container's /app/config directory
COPY ./config /app/config

# Expose the port specified in the configuration
EXPOSE 3000

ENV HOMEPAGE_VAR_SPEEDTEST_HREF=${SPEEDTEST_HREF}
ENV HOMEPAGE_VAR_SPEEDTEST_URL=${SPEEDTEST_URL}
ENV HOMEPAGE_VAR_ADGUARD_HREF=${ADGUARD_HREF}
ENV HOMEPAGE_VAR_ADGUARD_URL=${ADGUARD_URL}
ENV HOMEPAGE_VAR_ADGUARD_USERNAME=${ADGUARD_USERNAME}
ENV HOMEPAGE_VAR_ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
ENV HOMEPAGE_VAR_PLEX_HREF=${PLEX_HREF}
ENV HOMEPAGE_VAR_PLEX_TATUTULLI_URL=${PLEX_TATUTULLI_URL}
ENV HOMEPAGE_VAR_PLEX_TOKEN=${PLEX_TOKEN}
ENV HOMEPAGE_VAR_QBITT_HREF=${QBITT_HREF}
ENV HOMEPAGE_VAR_QBITT_URL=${QBITT_URL}
ENV HOMEPAGE_VAR_QBITT_USERNAME=${QBITT_USERNAME}
ENV HOMEPAGE_VAR_QBITT_PASSWORD=${QBITT_PASSWORD}
ENV HOMEPAGE_VAR_SONARR_HREF=${SONARR_HREF}
ENV HOMEPAGE_VAR_SONARR_URL=${SONARR_URL}
ENV HOMEPAGE_VAR_SONARR_KEY=${SONARR_KEY}
ENV HOMEPAGE_VAR_RADARR_HREF=${RADARR_HREF}
ENV HOMEPAGE_VAR_RADARR_KEY=${RADARR_KEY}
ENV HOMEPAGE_VAR_RADARR_URL=${RADARR_URL}