version: "3.8"

services:
    homepage:
        build:
          context: .
          dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - LOG_LEVEL=debug
            - SPEEDTEST_HREF=${SPEEDTEST_HREF}
            - SPEEDTEST_URL=${SPEEDTEST_URL}
            - ADGUARD_HREF=${ADGUARD_HREF}
            - ADGUARD_URL=${ADGUARD_URL}
            - ADGUARD_USERNAME=${ADGUARD_USERNAME}
            - ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
            - PLEX_HREF=${PLEX_HREF}
            - PLEX_TATUTULLI_URL=${PLEX_TATUTULLI_URL}
            - PLEX_TOKEN=${PLEX_TOKEN}
            - QBITT_HREF=${QBITT_HREF}
            - QBITT_URL=${QBITT_URL}
            - QBITT_USERNAME=${QBITT_USERNAME}
            - QBITT_PASSWORD=${QBITT_PASSWORD}
            - SONARR_HREF=${SONARR_HREF}
            - SONARR_URL=${SONARR_URL}
            - SONARR_KEY=${SONARR_KEY}
            - RADARR_HREF=${RADARR_HREF}
            - RADARR_KEY=${RADARR_KEY}
            - RADARR_URL=${RADARR_URL}
        # develop:
        #     watch:
        #         - action: rebuild
        #           path: ./config
