version: "3.8"

services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        ports:
          - 5999:3000
        volumes:
            - ./config:/app/config
        restart: unless-stopped
        environment:
            - PUID: "${USERID:-1000}"
            - PGID: "${GROUPID:-1000}"
            - LOG_LEVEL=debug
            - HOMEPAGE_VAR_SPEEDTEST_HREF=${SPEEDTEST_HREF}
            - HOMEPAGE_VAR_SPEEDTEST_URL=${SPEEDTEST_URL}
            - HOMEPAGE_VAR_ADGUARD_HREF=${ADGUARD_HREF}
            - HOMEPAGE_VAR_ADGUARD_URL=${ADGUARD_URL}
            - HOMEPAGE_VAR_ADGUARD_USERNAME=${ADGUARD_USERNAME}
            - HOMEPAGE_VAR_ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
            - HOMEPAGE_VAR_PLEX_HREF=${PLEX_HREF}
            - HOMEPAGE_VAR_PLEX_TATUTULLI_URL=${PLEX_TATUTULLI_URL}
            - HOMEPAGE_VAR_PLEX_TOKEN=${PLEX_TOKEN}
            - HOMEPAGE_VAR_QBITT_HREF=${QBITT_HREF}
            - HOMEPAGE_VAR_QBITT_URL=${QBITT_URL}
            - HOMEPAGE_VAR_QBITT_USERNAME=${QBITT_USERNAME}
            - HOMEPAGE_VAR_QBITT_PASSWORD=${QBITT_PASSWORD}
            - HOMEPAGE_VAR_SONARR_HREF=${SONARR_HREF}
            - HOMEPAGE_VAR_SONARR_URL=${SONARR_URL}
            - HOMEPAGE_VAR_SONARR_KEY=${SONARR_KEY}
            - HOMEPAGE_VAR_RADARR_HREF=${RADARR_HREF}
            - HOMEPAGE_VAR_RADARR_KEY=${RADARR_KEY}
            - HOMEPAGE_VAR_RADARR_URL=${RADARR_URL}
        # develop:
        #     watch:
        #         - action: rebuild
        #           path: ./config
